# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180324_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient', to='app.Nutrient'),
        ),
    ]
