# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 17:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180324_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.MaxLengthValidator(32, message='Food name must contain at                                most 32 characters'), django.core.validators.MinLengthValidator(2, message='Ingredient name must contain at                                least 2 characters')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='nutrients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient', to='app.Nutrient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.MaxLengthValidator(32, message='Ingredient name must contain at                                most 32 characters'), django.core.validators.MinLengthValidator(2, message='Ingredient name must contain at                                least 2 characters')]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(db_table='food_ingredients', to='app.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Nutrient'),
        ),
    ]
