# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180403_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(db_table='food_ingredients', related_name='recipes', to='app.Ingredient'),
        ),
    ]
