# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('regular_user', 'Regular User'), ('website_admin', 'Company admin'), ('super_admin', 'Super Admin')], default='regular_user', max_length=32),
        ),
    ]
