# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180403_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nutrients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Nutrient'),
        ),
    ]
