# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180403_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nutrient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient', to='app.Nutrient'),
        ),
    ]
